export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"

export const INIT_ORGANIZATIONS = "INIT_ORGANIZATIONS"
export const ADD_ORGANIZATION = "ADD_ORGANIZATION"

export const ADDPHOTO = "ADDPHOTO"

export const INIT_REQUEST_STUDENTS = 'INIT_REQUEST_STUDENTS'
export const INIT_REQUEST_STUDENT_PARAMS = 'INIT_REQUEST_STUDENT_PARAMS'

