export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"

export const INIT_ORGANIZATIONS = "INIT_ORGANIZATIONS"
export const ADD_ORGANIZATION = "ADD_ORGANIZATION"
export const INIT_ONE_OGRANIZATION = "INIT_ONE_OGRANIZATION"

export const ADD_PHOTO = "ADD_PHOTO"
export const UPDATE_USER = "UPDATE_USER"
export const ADD_RESUME = "ADD_RESUME"

export const INIT_REQUEST_STUDENTS = 'INIT_REQUEST_STUDENTS'
export const INIT_REQUEST_STUDENT_PARAMS = 'INIT_REQUEST_STUDENT_PARAMS'

export const ADD_VACANTION = 'ADD_VACANTION'
export const INIT_VACANTION = 'INIT_VACANTION'
export const INIT_ONE_VACANTION = 'INIT_ONE_VACANTION'

export const INIT_ALL_STUDENTS = 'INIT_ALL_STUDENTS'
export const INIT_SEARCH_STUDENTS = 'INIT_SEARCH_STUDENTS'
