export const SET_USER = "SET_USER"
export const LOGOUT = "LOGOUT"

export const INIT_ORGANIZATIONS = "INIT_ORGANIZATIONS"
export const ADD_ORGANIZATION = "ADD_ORGANIZATION"

export const ADDPHOTO = "ADDPHOTO"
export const APDATEUSER = "APDATEUSER"
export const ADDREZUME = "ADDREZUME"

export const INIT_REQUEST_STUDENTS = 'INIT_REQUEST_STUDENTS'
export const INIT_REQUEST_STUDENT_PARAMS = 'INIT_REQUEST_STUDENT_PARAMS'

export const ADD_VACANTION = 'ADD_VACANTION'
export const INIT_VACANTION = 'INIT_VACANTION'

